name: Deploy Supabase Resources
'on':
  push:
    branches:
      - production
  workflow_dispatch: null
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.0
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Run database migrations
        run: cd apps/supabase && supabase db push --project-ref ${{ secrets.PROJECT_ID }}
      
      - name: Deploy Supabase functions
        run: >-
          pnpm supabase:functions:deploy hello-world --project-ref ${{ secrets.PROJECT_ID }}
          --no-verify-jwt
